//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package org.apache.axis2.jaxws.sample.mtomfeature;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ProcessDocumentService", targetNamespace = "http://mtomfeature.sample.jaxws.axis2.apache.org/", wsdlLocation = "file:/C:/work/mtomfeature/ProcessDocumentService.wsdl")
public class ProcessDocumentService
extends Service
{

    private final static URL PROCESSDOCUMENTSERVICE_WSDL_LOCATION;
    private static String wsdlLocation="/test/org/apache/axis2/jaxws/sample/mtomfeature/META-INF/ProcessDocumentService.wsdl";
    static {
        URL url = null;
        try {
            try{
                String baseDir = new File(System.getProperty("basedir",".")).getCanonicalPath();
                wsdlLocation = new File(baseDir + wsdlLocation).getAbsolutePath();
            }catch(Exception e){
                e.printStackTrace();
            }
            File file = new File(wsdlLocation);
            url = file.toURI().toURL();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PROCESSDOCUMENTSERVICE_WSDL_LOCATION = url;
    }

    public ProcessDocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessDocumentService() {
        super(PROCESSDOCUMENTSERVICE_WSDL_LOCATION, new QName("http://mtomfeature.sample.jaxws.axis2.apache.org/", "ProcessDocumentService"));
    }

    /**
     * 
     * @return
     *     returns ProcessDocumentDelegate
     */
    @WebEndpoint(name = "ProcessDocumentPort")
    public ProcessDocumentDelegate getProcessDocumentPort() {
        return (ProcessDocumentDelegate)super.getPort(new QName("http://mtomfeature.sample.jaxws.axis2.apache.org/", "ProcessDocumentPort"), ProcessDocumentDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessDocumentDelegate
     */
    @WebEndpoint(name = "ProcessDocumentPort")
    public ProcessDocumentDelegate getProcessDocumentPort(WebServiceFeature... features) {
        return (ProcessDocumentDelegate)super.getPort(new QName("http://mtomfeature.sample.jaxws.axis2.apache.org/", "ProcessDocumentPort"), ProcessDocumentDelegate.class, features);
    }

}
