/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package org.apache.axis2.jaxws.sample.doclitbarenoarg.sei;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "BareDocLitNoArgService", targetNamespace = "http://sei.doclitbarenoarg.sample.jaxws.axis2.apache.org", wsdlLocation = "doclitbarenoarg.wsdl")
public class BareDocLitNoArgService
    extends Service
{

    private final static URL BAREDOCLITNOARGSERVICE_WSDL_LOCATION;
    
    private static String wsdlLocation = "/test/org/apache/axis2/jaxws/sample/doclitbarenoarg/META-INF/doclitbarenoarg.wsdl";
    static {
        URL url = null;
        try {
            String baseDir = new File(System.getProperty("basedir",".")).getCanonicalPath();
            wsdlLocation = new File(baseDir + wsdlLocation).getAbsolutePath();
            File file = new File(wsdlLocation);
            url = file.toURL();
//            url = new URL("file:/test/org/apache/axis2/jaxws/sample/doclitbarenoarg/META-INF/doclitbarenoarg.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        BAREDOCLITNOARGSERVICE_WSDL_LOCATION = url;
    }

    public BareDocLitNoArgService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BareDocLitNoArgService() {
        super(BAREDOCLITNOARGSERVICE_WSDL_LOCATION, new QName("http://sei.doclitbarenoarg.sample.jaxws.axis2.apache.org", "BareDocLitNoArgService"));
    }

    /**
     * 
     * @return
     *     returns DocLitBareNoArgPortType
     */
    @WebEndpoint(name = "BareDocLitNoArgPort")
    public DocLitBareNoArgPortType getBareDocLitNoArgPort() {
        return (DocLitBareNoArgPortType)super.getPort(new QName("http://sei.doclitbarenoarg.sample.jaxws.axis2.apache.org", "BareDocLitNoArgPort"), DocLitBareNoArgPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocLitBareNoArgPortType
     */
    @WebEndpoint(name = "BareDocLitNoArgPort")
    public DocLitBareNoArgPortType getBareDocLitNoArgPort(WebServiceFeature... features) {
        return (DocLitBareNoArgPortType)super.getPort(new QName("http://sei.doclitbarenoarg.sample.jaxws.axis2.apache.org", "BareDocLitNoArgPort"), DocLitBareNoArgPortType.class, features);
    }

}
