/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.apache.camel.component.msmq.native_support;

class msmq_native_supportJNI {
  public final static native int MQMSG_DELIVERY_EXPRESS_get();
  public final static native int MQMSG_DELIVERY_RECOVERABLE_get();
  public final static native int PROPID_M_CORRELATIONID_SIZE_get();
  public final static native int PROPID_M_MSGID_SIZE_get();
  public final static native int MQ_RECEIVE_ACCESS_get();
  public final static native int MQ_SEND_ACCESS_get();
  public final static native int INFINITE_get();
  public final static native long new_ByteArray(int jarg1);
  public final static native void delete_ByteArray(long jarg1);
  public final static native byte ByteArray_getitem(long jarg1, ByteArray jarg1_, int jarg2);
  public final static native void ByteArray_setitem(long jarg1, ByteArray jarg1_, int jarg2, byte jarg3);
  public final static native long ByteArray_cast(long jarg1, ByteArray jarg1_);
  public final static native long ByteArray_frompointer(long jarg1);

	static {
		try {
			//NativeLibraryLoader.loadLibrary("msmq_native_support");
			System.loadLibrary("msmq_native_support");
		} catch (Exception e) {
			System.loadLibrary("msmq_native_support");
		}
	}

  public final static native int MAXMSGSIZE_get();
  public final static native long new_MsmqMessage();
  public final static native void delete_MsmqMessage(long jarg1);
  public final static native void MsmqMessage_setAppSpecifc(long jarg1, MsmqMessage jarg1_, long jarg2);
  public final static native long MsmqMessage_getAppSpecific(long jarg1, MsmqMessage jarg1_);
  public final static native long MsmqMessage_getArrivedTime(long jarg1, MsmqMessage jarg1_);
  public final static native void MsmqMessage_setMsgBody(long jarg1, MsmqMessage jarg1_, long jarg2);
  public final static native void MsmqMessage_setMsgBodyWithByteBuffer(long jarg1, MsmqMessage jarg1_, java.nio.ByteBuffer jarg2);
  public final static native long MsmqMessage_getBodyType(long jarg1, MsmqMessage jarg1_);
  public final static native void MsmqMessage_setBodySize(long jarg1, MsmqMessage jarg1_, long jarg2);
  public final static native long MsmqMessage_getBodySize(long jarg1, MsmqMessage jarg1_);
  public final static native void MsmqMessage_setCorrelationId(long jarg1, MsmqMessage jarg1_, byte[] jarg2);
  public final static native void MsmqMessage_getCorrelationId(long jarg1, MsmqMessage jarg1_, byte[] jarg2);
  public final static native void MsmqMessage_setDelivery(long jarg1, MsmqMessage jarg1_, long jarg2);
  public final static native long MsmqMessage_getDelivery(long jarg1, MsmqMessage jarg1_);
  public final static native void MsmqMessage_getMsgId(long jarg1, MsmqMessage jarg1_, byte[] jarg2);
  public final static native void MsmqMessage_setPriority(long jarg1, MsmqMessage jarg1_, long jarg2);
  public final static native long MsmqMessage_getPriority(long jarg1, MsmqMessage jarg1_);
  public final static native long MsmqMessage_getSentTime(long jarg1, MsmqMessage jarg1_);
  public final static native void MsmqMessage_setTimeToBeReceived(long jarg1, MsmqMessage jarg1_, long jarg2);
  public final static native long MsmqMessage_getTimeToBeReceived(long jarg1, MsmqMessage jarg1_);
  public final static native long new_MsmqQueue();
  public final static native void delete_MsmqQueue(long jarg1);
  public final static native void MsmqQueue_open(long jarg1, MsmqQueue jarg1_, String jarg2, int jarg3);
  public final static native void MsmqQueue_sendMessage(long jarg1, MsmqQueue jarg1_, long jarg2, MsmqMessage jarg2_);
  public final static native boolean MsmqQueue_receiveMessage(long jarg1, MsmqQueue jarg1_, long jarg2, MsmqMessage jarg2_, int jarg3);
  public final static native void MsmqQueue_close(long jarg1, MsmqQueue jarg1_);
  public final static native boolean MsmqQueue_isOpen(long jarg1, MsmqQueue jarg1_);
  public final static native void MsmqQueue_createQueue(String jarg1);
  public final static native void MsmqQueue_deleteQueue(String jarg1);
}
