<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://sei.doclitbarenoarg.sample.jaxws.axis2.apache.org"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DoclitBareNoArg"
    targetNamespace="http://sei.doclitbarenoarg.sample.jaxws.axis2.apache.org">
    
    <wsdl:types>
        <xsd:schema
            targetNamespace="http://sei.doclitbarenoarg.sample.jaxws.axis2.apache.org"
            xmlns:tns="http://sei.doclitbarenoarg.sample.jaxws.axis2.apache.org"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:element name="String" type="xsd:string" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="NoParam" />

    <wsdl:message name="echoStringOut">
        <wsdl:part name="echoStringOut" element="tns:String" />
    </wsdl:message>

    <wsdl:portType name="DocLitBareNoArgPortType">
        <wsdl:operation name="twoWayEmpty">
            <wsdl:input message="tns:NoParam" />
            <wsdl:output message="tns:echoStringOut" />
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="DocLitBareNoArg" type="tns:DocLitBareNoArgPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="twoWayEmpty">
            <wsdl:input>
                <soap:body use="literal"  />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"  />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="BareDocLitNoArgService">
        <wsdl:port binding="tns:DocLitBareNoArg" name="BareDocLitNoArgPort">
            <soap:address location="http://localhost:6060/axis2/services/BareDocLitNoArgService" />
        </wsdl:port>
    </wsdl:service>
    
</wsdl:definitions>