<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://mtomfeature.sample.jaxws.axis2.apache.org/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ProcessDocumentService"
	targetNamespace="http://mtomfeature.sample.jaxws.axis2.apache.org/">
	<types>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:tns="http://mtomfeature.sample.jaxws.axis2.apache.org/"
			targetNamespace="http://mtomfeature.sample.jaxws.axis2.apache.org/" version="1.0">

			<xs:element name="sendPDFFile" type="tns:sendPDFFile" />

			<xs:element name="sendPDFFileResponse" type="tns:sendPDFFileResponse" />

			<xs:complexType name="sendPDFFile">
				<xs:sequence>
					<xs:element minOccurs="0" name="arg0" type="xs:base64Binary"
						xmime:expectedContentTypes="*/*" />
				</xs:sequence>
			</xs:complexType>

			<xs:complexType name="sendPDFFileResponse">
				<xs:sequence>
					<xs:element minOccurs="0" name="return" type="xs:base64Binary"
						xmime:expectedContentTypes="*/*" />
				</xs:sequence>
			</xs:complexType>
		</xs:schema>
	</types>

	<message name="sendPDFFile">
		<part element="tns:sendPDFFile" name="parameters" />
	</message>
	<message name="sendPDFFileResponse">
		<part element="tns:sendPDFFileResponse" name="parameters" />
	</message>
	<portType name="ProcessDocumentDelegate">
		<operation name="sendPDFFile">
			<input message="tns:sendPDFFile" />
			<output message="tns:sendPDFFileResponse" />
		</operation>
	</portType>
	<binding name="ProcessDocumentPortBinding" type="tns:ProcessDocumentDelegate">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="sendPDFFile">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="ProcessDocumentService">
		<port binding="tns:ProcessDocumentPortBinding" name="ProcessDocumentPort">
			<soap:address
				location="http://localhost:9080/MTOM/ProcessDocumentService" />
		</port>
	</service>
</definitions>
