<?xml version="1.0" encoding="UTF-8"?>
<wsdl11:definitions name="stock"
	targetNamespace="http://www.example.com/stock" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://www.example.com/stock"
	xmlns:wsdl11="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<wsdl11:types>
		<xsd:schema elementFormDefault="qualified"
			targetNamespace="http://www.example.com/stock" xmlns="http://www.w3.org/2001/XMLSchema">
			<element name="GetLastTradePriceResponse">
				<complexType>
					<sequence>
						<element name="return" type="xsd:int" />
					</sequence>
				</complexType>
			</element>

			<element name="GetLastTradePrice">
				<complexType>
					<sequence>
						<element name="arg0" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
		</xsd:schema>
	</wsdl11:types>

	<wsdl11:message name="GetLastTradePrice">
		<wsdl11:part element="tns:GetLastTradePrice" name="symbol" />
	</wsdl11:message>

	<wsdl11:message name="GetLastTradePriceResponse">
		<wsdl11:part element="tns:GetLastTradePriceResponse" name="result" />
	</wsdl11:message>

	<wsdl11:portType name="Quote">
		<wsdl11:operation name="GetLastTradePrice">
			<wsdl11:input message="tns:GetLastTradePrice" />
			<wsdl11:output message="tns:GetLastTradePriceResponse" />
		</wsdl11:operation>
	</wsdl11:portType>


</wsdl11:definitions>