<?xml version="1.0" encoding="UTF-8"?>
<wsdl11:definitions name="StockQuote"
	targetNamespace="http://www.example.com/stock/binding" xmlns:tns="http://www.example.com/stock/binding"
	xmlns:fab="http://www.example.com/stock" xmlns:rmp="http://docs.oasis-open.org/ws-rx/wsrmp/200702"
	xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
	xmlns:wsdl11="http://schemas.xmlsoap.org/wsdl/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:wsp="http://www.w3.org/ns/ws-policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
	
	<wsp:Policy wsu:Id="RmPolicy">
		<rmp:RMAssertion>
			<wsp:Policy />
		</rmp:RMAssertion>
	</wsp:Policy>
	<wsp:Policy wsu:Id="X509EndpointPolicy">
		<sp:AsymmetricBinding>
			<wsp:Policy>
				<!-- Details omitted for readability -->
				<sp:IncludeTimestamp />
				<sp:OnlySignEntireHeadersAndBody />
			</wsp:Policy>
		</sp:AsymmetricBinding>
	</wsp:Policy>
	<wsp:Policy wsu:Id="SecureMessagePolicy">
		<sp:SignedParts>
			<sp:Body />
		</sp:SignedParts>
		<sp:EncryptedParts>
			<sp:Body />
		</sp:EncryptedParts>
	</wsp:Policy>
	
	<wsdl11:import namespace="http://www.example.com/stock"
		location="stock.wsdl" />
	
	
	<wsdl11:binding name="StockQuoteSoapBinding" type="fab:Quote">
		<wsoap12:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsp:PolicyReference URI="#RmPolicy"
			wsdl11:required="true" />
		<wsp:PolicyReference URI="#X509EndpointPolicy"
			wsdl11:required="true" />
		<wsdl11:operation name="GetLastTradePrice">
			<wsoap12:operation
				soapAction="http://www.example.com/stock/Quote/GetLastTradePriceRequest" />
			<wsdl11:input>
				<wsoap12:body use="literal" />
				<wsp:PolicyReference URI="#SecureMessagePolicy"
					wsdl11:required="true" />
			</wsdl11:input>
			<wsdl11:output>
				<wsoap12:body use="literal" />
				<wsp:PolicyReference URI="#SecureMessagePolicy"
					wsdl11:required="true" />
			</wsdl11:output>
		</wsdl11:operation>
	</wsdl11:binding>
		<wsdl11:service name="StockQuoteService">
		<wsdl11:port binding="tns:StockQuoteSoapBinding" name="Quote">
			<wsoap12:address
				location="http://@HOST@:@PORT@/RespectBinding/StockQuoteService" />
		</wsdl11:port>
	</wsdl11:service>
</wsdl11:definitions>
