# This workflow will build the project on pull requests with tests
# Uses:
#   OS: ubuntu-latest
#   JDK: Temurin JDK 21

name: PR Builder

on:
  pull_request:
    branches:
      - 4.6.x
      - 4.7.x
      - 4.8.x
      - 4.9.x
  workflow_dispatch:

env:
  MAVEN_OPTS: -Xmx4g -Xms1g
  JDK_JAVA_OPTIONS: "--add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Cache local Maven repository
        id: cache-maven-m2
        uses: actions/cache@v2
        env:
          cache-name: cache-m2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ env.cache-name }}-
            ${{ runner.os }}-maven-
            ${{ runner.os }}-
      - name: Build with Maven
        run: mvn clean install -U -B
